# Generated by Django 3.0.5 on 2020-07-07 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryBudget',
        ),
    ]
