# Generated by Django 3.1.3 on 2020-12-23 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_avgquarterbudget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avgquarterbudget',
            name='remainder',
        ),
        migrations.RemoveField(
            model_name='constantbudget',
            name='remainder',
        ),
    ]
