# Generated by Django 3.1.3 on 2020-12-23 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20201223_0723'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvgQuarterBudget',
        ),
    ]
