# Generated by Django 3.1.3 on 2020-12-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_scheduledbudget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledbudget',
            name='last_date',
            field=models.DateField(help_text='YYYY-MM-DD Important: Make sure last date is first one that month'),
        ),
    ]
