# Generated by Django 4.1.5 on 2023-03-16 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_auto_20210103_0939'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpecificBudget',
        ),
    ]
