# Generated by Django 4.1.5 on 2023-03-25 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_category_remainder_categorygroup_remainder'),
        ('budget', '0009_delete_specificbudget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledbudget',
            name='last_date',
            field=models.DateField(help_text='YYYY-MM-DD'),
        ),
        migrations.CreateModel(
            name='SpecifiedBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('last_date', models.DateField(help_text='YYYY-MM-DD')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('categorygroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.categorygroup')),
            ],
        ),
    ]
