# Generated by Django 4.1.5 on 2023-03-25 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_alter_scheduledbudget_last_date_specifiedbudget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specifiedbudget',
            old_name='last_date',
            new_name='date',
        ),
    ]
