# Generated by Django 4.1.5 on 2023-03-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0011_rename_last_date_specifiedbudget_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledbudget',
            name='last_date',
            field=models.DateField(help_text='YYYY-MM-DD: Make sure you enter the correct date!'),
        ),
        migrations.AlterField(
            model_name='specifiedbudget',
            name='date',
            field=models.DateField(help_text='YYYY-MM-DD: Make sure you enter the correct date!'),
        ),
    ]
