# Generated by Django 3.1.4 on 2021-02-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_account_is_creditcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_creditcard',
            field=models.BooleanField(default=False),
        ),
    ]
