# Generated by Django 3.1.4 on 2021-02-07 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_creditcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='bill_date',
            field=models.DateField(blank=True, default=datetime.date(2021, 2, 7)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcard',
            name='payment_scheduled_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcard',
            name='payment_scheduled_date',
            field=models.DateField(blank=True, default=datetime.date(2021, 2, 7)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcard',
            name='statement_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
    ]
