# Generated by Django 4.1.5 on 2023-03-13 14:22

from django.db import migrations, models
import django.db.models.deletion
import transaction.models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_alter_category_name'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(default=transaction.models.get_none_category, on_delete=django.db.models.deletion.SET_DEFAULT, to='category.category'),
        ),
    ]
