# Generated by Django 4.1.5 on 2023-03-13 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_transaction_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledtransaction',
            name='category',
        ),
        migrations.DeleteModel(
            name='SavedTransaction',
        ),
        migrations.DeleteModel(
            name='ScheduledTransaction',
        ),
    ]
