# Generated by Django 3.1.3 on 2020-11-28 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0011_auto_20200707_0810'),
        ('transaction', '0005_scheduledtransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saved_Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='category.category')),
            ],
        ),
    ]
