# Generated by Django 3.1.3 on 2020-11-28 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0011_auto_20200707_0810'),
        ('transaction', '0006_saved_transaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Saved_Transaction',
            new_name='SavedTransaction',
        ),
    ]
