# Generated by Django 3.1.3 on 2020-11-30 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_auto_20201127_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduledtransaction',
            old_name='working_date',
            new_name='scheduled_date',
        ),
    ]
