# Generated by Django 3.1.3 on 2020-11-30 12:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0011_auto_20200707_0810'),
        ('transaction', '0008_auto_20201130_0730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledtransaction',
            name='transaction',
        ),
        migrations.AddField(
            model_name='scheduledtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduledtransaction',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='category.category'),
        ),
        migrations.AddField(
            model_name='scheduledtransaction',
            name='date',
            field=models.DateField(default=datetime.date(2020, 11, 30)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduledtransaction',
            name='description',
            field=models.CharField(default='Test', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
