# Generated by Django 3.1.3 on 2020-11-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_auto_20201130_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledtransaction',
            name='date',
        ),
        migrations.AlterField(
            model_name='scheduledtransaction',
            name='repeat_every',
            field=models.CharField(choices=[('AM', 'Repeat Monthly on Approx. Specific Date'), ('AB', 'Repeat Bi-Weekly on Approx. Specific Date'), ('SM', 'Repeat Monthly on Specific Date'), ('B', 'Repeat Bi-Weekly based on Initial Date')], max_length=2),
        ),
        migrations.AlterField(
            model_name='scheduledtransaction',
            name='scheduled_date',
            field=models.DateField(),
        ),
    ]
