# Generated by Django 3.1.3 on 2020-12-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0010_auto_20201130_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtransaction',
            name='repeat_every',
            field=models.CharField(choices=[('M', 'Monthly'), ('B', 'Bi-Weekly')], max_length=2),
        ),
    ]
