# Generated by Django 3.1.3 on 2020-12-21 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('budget_method', models.CharField(choices=[('N', 'None'), ('C', 'Constant Month to Month'), ('A', 'Averaged over last few months'), ('S', 'Scheduled Transactions'), ('Y', 'Based on Last Year')], default='N', max_length=1)),
            ],
            options={
                'verbose_name': 'Category Group',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('budget_method', models.CharField(choices=[('N', 'None'), ('C', 'Constant Month to Month'), ('A', 'Averaged over last few months'), ('S', 'Scheduled Transactions'), ('Y', 'Based on Last Year')], default='N', max_length=1)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.categorygroup')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
