# Generated by Django 3.1.3 on 2020-12-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20201222_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='remainder',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='categorygroup',
            name='remainder',
            field=models.BooleanField(default=True),
        ),
    ]
