# Generated by Django 3.0.5 on 2020-04-22 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20191014_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='group',
        ),
        migrations.DeleteModel(
            name='CategoryGroup',
        ),
    ]
