# Generated by Django 3.1.3 on 2020-12-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20201223_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorygroup',
            name='remainder',
            field=models.BooleanField(default=True, help_text='Check if pot of money.'),
        ),
    ]
