# Generated by Django 4.1.5 on 2023-03-14 16:57

import category.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='group',
            field=models.ForeignKey(default=category.models.get_uncategorized_group, on_delete=django.db.models.deletion.SET_DEFAULT, to='category.categorygroup'),
        ),
    ]
