# Generated by Django 3.0.5 on 2020-07-03 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_auto_20200703_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorygroup',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.CategoryGroup'),
        ),
    ]
