# Generated by Django 4.1.5 on 2023-03-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_remove_category_remainder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='remainder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categorygroup',
            name='remainder',
            field=models.BooleanField(default=False),
        ),
    ]
