# Generated by Django 3.0.5 on 2020-07-03 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_categorygroup_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorygroup',
            name='parent',
        ),
    ]
