# Generated by Django 3.0.5 on 2020-07-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_remove_categorygroup_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorygroup',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
