# Generated by Django 3.0.5 on 2020-07-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0010_auto_20200703_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='categorygroup',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
