# Generated by Django 3.1.3 on 2020-12-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0011_auto_20200707_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='categorygroup',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
