# Generated by Django 4.1.5 on 2023-01-06 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_auto_20201226_0750'),
        ('envelope', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envelope',
            name='categorygroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.categorygroup'),
        ),
    ]
