# Generated by Django 4.1.5 on 2023-03-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelope', '0002_alter_envelope_categorygroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelope',
            name='excclude_carryover',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='envelope',
            name='exclude_plus_minus',
            field=models.BooleanField(default=False),
        ),
    ]
