# Generated by Django 4.1.5 on 2023-03-04 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envelope', '0003_envelope_excclude_carryover_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='envelope',
            old_name='excclude_carryover',
            new_name='exclude_carryover',
        ),
    ]
