# Generated by Django 4.1.5 on 2023-03-04 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envelope', '0004_rename_excclude_carryover_envelope_exclude_carryover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envelope',
            name='exclude_carryover',
        ),
        migrations.RemoveField(
            model_name='envelope',
            name='exclude_plus_minus',
        ),
    ]
