# Generated by Django 4.1.5 on 2023-03-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelope', '0005_remove_envelope_exclude_carryover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelope',
            name='reset_carryover',
            field=models.BooleanField(default=False),
        ),
    ]
