# Generated by Django 4.1.5 on 2023-03-05 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envelope', '0006_envelope_reset_carryover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envelope',
            name='plus_minus',
        ),
        migrations.RemoveField(
            model_name='envelope',
            name='reset_carryover',
        ),
    ]
