# Generated by Django 4.1.5 on 2023-03-16 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envelope', '0007_remove_envelope_plus_minus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envelope',
            name='carryover',
        ),
    ]
